Repository Team1559/2020-2021-InfiniteRecharge, pull requests merged in 2020-02, with the labels that each got.

#65 added current graphing
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/Chassis.java
Labels: New Feature

#66 feature flags
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
  2020-InfiniteRecharge/src/main/java/frc/robot/components/CompressorControl.java
Labels: Feature Addition, Organization

#78 Cleaned up code and added comments for Control Panel
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
  2020-InfiniteRecharge/src/main/java/frc/robot/Wiring.java
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/Spinner.java
Labels: Organization

#80 updated feature flags
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
Labels: Feature Addition

#81 Climber code is finished
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/Climber.java
Labels: New Feature

#73 Set feeder to position mode when stopped
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/PowerCell.java
Labels: Feature Addition

#83 Power cell shooter on shuffleboard
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/PowerCell.java
Labels: New Feature, Organization

#85 Updating the project to WPILib 2020.2.2
  2020-InfiniteRecharge/build.gradle
Labels: Organization, documentation

#96 Completed drivetrain and power cell
  2020-InfiniteRecharge/src/main/java/frc/robot/Robot.java
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/PowerCell.java
Labels: Test

#115 Power cell stuff
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/Auto.java
  2020-InfiniteRecharge/src/main/java/frc/robot/subsystems/PowerCell.java
Labels: Feature Addition, Test, Tuning
